# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureFreeSubscription(83141d16-bd7c-47b0-b935-1565e697a8e6)'
    appType: 'webAppLinux'
    appName: 'MyDevPrj'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'TOMCAT|9.0-java11'
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
